# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('curr_matchday', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 11, 19, 42, 1, 470000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='res',
            field=models.CharField(choices=[('1', 'HOME-WIN'), ('X', 'TIE'), ('2', 'AWAY-WIN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bet',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 11, 19, 42, 1, 470000, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='casino.League'),
        ),
    ]
