# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0002_auto_20161011_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='name',
            field=models.CharField(default='-', max_length=28),
        ),
        migrations.AlterField(
            model_name='bet',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 11, 19, 52, 29, 819000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 11, 19, 52, 29, 819000, tzinfo=utc), editable=False),
        ),
    ]
