# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0003_auto_20161011_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bet',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='time_created',
        ),
        migrations.AlterField(
            model_name='bet',
            name='res',
            field=models.CharField(choices=[('1', 'HOME WIN'), ('X', 'DRAW'), ('2', 'AWAY WIN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='competition',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='casino.Team'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='casino.Team'),
        ),
    ]
