# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0007_auto_20161015_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='form',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='bet',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 15, 13, 16, 6, 769000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 15, 13, 16, 6, 769000, tzinfo=utc)),
        ),
    ]
