# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0008_auto_20161015_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2016, 10, 15, 21, 20, 0, 176000, tzinfo=utc), editable=False)),
                ('key', models.CharField(blank=True, max_length=17)),
                ('username', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 15, 21, 20, 0, 176000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 15, 21, 20, 0, 176000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='league',
            name='curr_matchday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='form',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
