# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casino', '0009_auto_20161016_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gambler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2016, 10, 22, 16, 35, 10, 273000, tzinfo=utc), editable=False)),
                ('favourite_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='casino.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_gamblers', models.IntegerField(default=0)),
                ('gamblers', models.ManyToManyField(to='casino.Gambler')),
            ],
        ),
        migrations.AlterField(
            model_name='activationkey',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 16, 35, 10, 294000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 16, 35, 10, 289000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 16, 35, 10, 289000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='competition',
            name='groups',
            field=models.ManyToManyField(to='casino.Group'),
        ),
    ]
