# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0010_auto_20161022_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 16, 37, 39, 451000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 16, 37, 39, 448000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='casino.Gambler'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 16, 37, 39, 448000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gambler',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 16, 37, 39, 444000, tzinfo=utc), editable=False),
        ),
    ]
