# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0011_auto_20161022_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='gamblers',
            new_name='admins',
        ),
        migrations.AddField(
            model_name='group',
            name='bets',
            field=models.ManyToManyField(to='casino.Bet'),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='activationkey',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 10, 47, 13, 993000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 10, 47, 13, 992000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 10, 47, 13, 992000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gambler',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 23, 10, 47, 13, 986000, tzinfo=utc), editable=False),
        ),
    ]
