# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0012_auto_20161023_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='group',
            name='bets',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='groups',
        ),
        migrations.AddField(
            model_name='competition',
            name='bets',
            field=models.ManyToManyField(to='casino.Bet'),
        ),
        migrations.AlterField(
            model_name='activationkey',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 27, 18, 32, 53, 242000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 27, 18, 32, 53, 242000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 27, 18, 32, 53, 242000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gambler',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 27, 18, 32, 53, 227000, tzinfo=utc), editable=False),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
